### ISSUE TITLE
PROJECT Gangplank E blast bug

### ISSUE THREAD

**Issue by yizhizhuguagua** [koobzaar/lol-skins#58]
![9e6ba9f3aa4ac27e3af11239b2acbcc2](https://github.com/user-attachments/assets/99171849-9cb3-4282-b5e5-04da6b52340e)

**Comment by koobzaar** [comment]
PROJECT: Gangplank's base skin and chromas are working fine, so the issue seems to be with your game. Please everytime you open an issue, clarify if the problem is with the base skin or a chroma. If you need any help with that, use the issue template.
Footage:

https://github.com/user-attachments/assets/474e4194-adc5-42c7-b347-1c753ee0e4e1


https://github.com/user-attachments/assets/2b03875b-6698-4ba4-9ae8-e93ee744523d

**Comment by yizhizhuguagua** [comment]
Sorry, I made a mistake Clearing game cache is normal now
